name: Deploy API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: backend

jobs:

  deploy:
      name: Deploy
      runs-on: ubuntu-latest

      steps: 
        - name: Checkout
          uses: actions/checkout@v1

        - name: Deploy Backend API
          uses: digitalocean/app_action@main
          with:
            app_name: calorie-tracker-prod
            token: ${{ secrets.SECRET_KEY }}